# 민감정보 설정파일
# 실제 서비스시 배포서버의 Docker 에서 외부주입으로 해결 필요
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.je0ngyun.kro.kr:3306/cardme?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: dev
    password: summer9830
jwt:
  secret-key: "kimjeongyun"
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: xptmxm